import { NextResponse } from 'next/server';
import { GoogleGenAI } from '@google/genai';
import { SerializableNode, SerializableEdge } from '@/types/canvas';

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY || '' });

const AI_MODELS = [
  'gemini-3.7-flash',
  'gemini-3.6-flash',
  'gemini-3.5-flash',
  'gemini-3.8-flash',
];

async function withModelFallback<T>(
  models: string[],
  fn: (model: string) => Promise<T>
): Promise<T> {
  let lastError: unknown;
  for (const model of models) {
    try {
      return await fn(model);
    } catch (e) {
      lastError = e;
      console.warn(`Model ${model} unavailable for study guide export, trying next...`);
    }
  }
  throw lastError;
}

interface ExportRequestBody {
  boardTitle: string;
  nodes: SerializableNode[];
  edges?: SerializableEdge[];
  format: 'sermon' | 'small_group' | 'exegetical';
  theologicalLens?: string;
}

function generateLocalFallbackGuide(
  boardTitle: string,
  nodes: SerializableNode[],
  format: 'sermon' | 'small_group' | 'exegetical'
): string {
  const scriptureNodes = nodes.filter(n => n.data.category === 'scripture');
  const theologicalNodes = nodes.filter(n => n.data.category === 'theological_point');
  const historicalNodes = nodes.filter(n => n.data.category === 'historical_context');
  const applicationNodes = nodes.filter(n => n.data.category === 'application');
  const illustrationNodes = nodes.filter(n => n.data.category === 'illustration');

  if (format === 'sermon') {
    return `# Expository Sermon Outline: ${boardTitle || 'Walking in God\'s Truth'}

## Big Idea / Proposition
${theologicalNodes[0]?.data.content || 'God reveals His transformative truth through His Word to reshape our hearts and lives.'}

---

## I. Biblical Foundation & Textual Anchor
${scriptureNodes.map(s => `### ${s.data.title}\n${s.data.content}\n`).join('\n') || '- Scripture anchor established from canvas study.'}

## II. Historical & Redemptive Context
${historicalNodes.map(h => `- **${h.data.title}**: ${h.data.content}`).join('\n') || '- Grounded in biblical history and canonical fulfillment.'}

## III. Theological Exposition & Core Doctrine
${theologicalNodes.map((t, idx) => `### Point ${idx + 1}: ${t.data.title}\n${t.data.content}\n`).join('\n') || '- Core biblical doctrines explored.'}

## IV. Pastoral Illustrations
${illustrationNodes.map(i => `- **${i.data.title}**: ${i.data.content}`).join('\n') || '- Illustrated through faithful life examples.'}

## V. Pastoral Call to Action & Conclusion
${applicationNodes.map(a => `- **${a.data.title}**: ${a.data.content}`).join('\n') || '- Respond in faith, repentance, and obedience.'}

---
*Generated by Theologica Study Workbench*`;
  }

  if (format === 'small_group') {
    return `# Small Group Bible Study Guide: ${boardTitle || 'Scripture Discovery'}

## Icebreaker & Opening Question
- When you consider the themes of this passage, how do you see people in modern culture searching for this same hope or answers?

---

## 1. Scripture Reading
${scriptureNodes.map(s => `> **${s.data.title}**\n>\n> ${s.data.content.replace(/\n/g, '\n> ')}\n`).join('\n')}

## 2. Background & Context
${historicalNodes.map(h => `* **${h.data.title}**: ${h.data.content}`).join('\n') || '* Consider the original audience and redemptive situation.'}

## 3. Observation Questions (What does the text say?)
1. What repeated words, theological themes, or key commands stand out in this text?
2. How does the biblical author establish their primary argument?

## 4. Interpretation Questions (What does it mean?)
${theologicalNodes.map(t => `- **Regarding ${t.data.title}**: How does this doctrinal reality clarify God's character and gospel grace?`).join('\n') || '- How does this passage point to God\'s redemptive plan in Christ?'}

## 5. Personal Application (What does it mean for us?)
${applicationNodes.map(a => `- **${a.data.title}**: How can we practically put this into action in our homes, workplaces, and church community this week?`).join('\n') || '- What is one practical step of obedience you are called to take today?'}

## 6. Closing Prayer Focus
- Lift up prayers of thanksgiving for the truth received, praying for grace to walk in faithfulness.

---
*Theologica Small Group Resources*`;
  }

  return `# Exegetical & Hermeneutical Brief: ${boardTitle}

## 1. Textual & Canonical Scope
${scriptureNodes.map(s => `- **${s.data.title}**\n  ${s.data.content}`).join('\n\n')}

## 2. Historical-Grammatical Background
${historicalNodes.map(h => `### ${h.data.title}\n${h.data.content}`).join('\n\n')}

## 3. Theological Synthesis & Systematic Correlation
${theologicalNodes.map(t => `### ${t.data.title}\n${t.data.content}`).join('\n\n')}

## 4. Practical & Ethical Implications
${applicationNodes.map(a => `- **${a.data.title}**: ${a.data.content}`).join('\n')}

---
*Theologica Academic Brief*`;
}

export async function POST(req: Request) {
  try {
    const body: ExportRequestBody = await req.json();
    const { boardTitle, nodes, edges, format, theologicalLens = 'canonical' } = body;

    if (!nodes || nodes.length === 0) {
      return NextResponse.json({
        content: `# ${boardTitle || 'Untitled Study'}\n\n*No cards found on canvas to synthesize. Add scripture and notes to generate a study guide!*`
      });
    }

    const cardsSummary = nodes.map((n, i) => {
      return `[Card ${i + 1}] Category: ${n.data.category} | Title: "${n.data.title}"\nContent: ${n.data.content}\n`;
    }).join('\n---\n');

    let formatInstructions = '';
    if (format === 'sermon') {
      formatInstructions = `Create a comprehensive, compelling, homiletically sound EXPOSITORY SERMON OUTLINE suitable for preaching or teaching.
Include:
1. Title and Compelling Hook
2. Big Idea / Proposition (1 clear sentence)
3. Historical & Redemptive Setting
4. Clear Main Points (Roman numerals I, II, III) with subpoints, Scripture citations, and biblical argumentation
5. Pastoral Illustrations based on the canvas cards
6. Practical Application & Final Call to Repentance / Faith / Obedience`;
    } else if (format === 'small_group') {
      formatInstructions = `Create a complete, engaging, interactive SMALL GROUP BIBLE STUDY DISCUSSION GUIDE.
Include:
1. Catchy Study Title & Warm-up Icebreaker
2. Scripture Reading Block with clear citations
3. Brief Context / Setting (2-3 sentences)
4. Observation Questions (inductive: what does the text literally say?)
5. Interpretation Questions (theological: what does it mean in light of Christ and the gospel?)
6. Life Application Discussion (concrete, personal transformation)
7. Prayer Prompts & Weekly Action Step`;
    } else {
      formatInstructions = `Create a rigorous, structured EXEGETICAL AND THEOLOGICAL BRIEF.
Include:
1. Textual Analysis & Canonical Context
2. Historical-Grammatical Setting
3. Original Language & Lexical Insights
4. Doctrinal Proposition & Systematic Theology Links
5. Hermeneutical Conclusions & Homiletical Takeaway`;
    }

    const lensInstruction = theologicalLens !== 'canonical'
      ? `Apply a ${theologicalLens.toUpperCase()} theological lens: reflect the hermeneutical priorities, historical citations, and tone of the ${theologicalLens} tradition.`
      : 'Maintain a faithful, canonical, Christ-centered biblical perspective.';

    const systemPrompt = `You are the master theological homiletics and curriculum engine for Theologica. Your task is to transform visual mind-map cards from a user's Bible study canvas into an impeccably formatted, rich, ready-to-teach Markdown document.

${lensInstruction}

MANDATORY RULES:
- Format completely in clean GitHub-flavored Markdown.
- Incorporate all the user's specific cards, scripture verses, theological points, and notes naturally.
- Ensure all Scripture citations are bolded in standard format (e.g. **Romans 8:28**, **John 1:1-5**).
- Do not add conversational intro/outro text (e.g. "Here is your sermon outline:"). Output ONLY the final markdown document.`;

    try {
      const guideText = await withModelFallback(AI_MODELS, async (model) => {
        const response = await ai.models.generateContent({
          model,
          contents: `${formatInstructions}\n\nBoard Title: "${boardTitle}"\n\nCANVAS CARDS DATA:\n${cardsSummary}`,
          config: {
            systemInstruction: systemPrompt,
            temperature: 0.35,
          }
        });
        return response.candidates?.[0]?.content?.parts?.[0]?.text?.trim() || '';
      });

      if (guideText) {
        return NextResponse.json({ content: guideText });
      }
    } catch (aiErr) {
      console.warn('AI study guide generation failed, using intelligent local synthesis:', aiErr);
    }

    // Fallback to high-quality local structured template
    const fallbackText = generateLocalFallbackGuide(boardTitle, nodes, format);
    return NextResponse.json({ content: fallbackText });
  } catch (err: any) {
    console.error('Error generating export study guide:', err);
    return NextResponse.json(
      { error: err?.message || 'Failed to generate study guide' },
      { status: 500 }
    );
  }
}
